In [1]:
# 탑건 url 가져오기

#mainContent > div > div.box_boxoffice > ol > li:nth-child(1) > div > div.thumb_cont > strong > a

In [2]:
from bs4 import BeautifulSoup
from urllib.request import urlopen
import pandas as pd

In [3]:
url = "https://movie.daum.net/ranking/boxoffice/weekly"
page = urlopen(url)
soup = BeautifulSoup(page, 'html.parser')

In [4]:
li_lists = soup.select("#mainContent > div > div.box_boxoffice > ol > li > div > div.thumb_cont > strong > a")

In [5]:
li_lists = soup.select(".link_txt")
li_lists

[<a class="link_txt" href="/moviedb/main?movieId=114329">탑건: 매버릭</a>,
 <a class="link_txt" href="/moviedb/main?movieId=146758">마녀(魔女) Part2. The Other One</a>,
 <a class="link_txt" href="/moviedb/main?movieId=122749">범죄도시 2</a>,
 <a class="link_txt" href="/moviedb/main?movieId=144096">브로커</a>,
 <a class="link_txt" href="/moviedb/main?movieId=155087">버즈 라이트이어</a>,
 <a class="link_txt" href="/moviedb/main?movieId=139235">쥬라기 월드: 도미니언</a>,
 <a class="link_txt" href="/moviedb/main?movieId=160414">극장판 윌벤져스 : 수상한 캠핑 대소동</a>,
 <a class="link_txt" href="/moviedb/main?movieId=47111">극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미</a>,
 <a class="link_txt" href="/moviedb/main?movieId=144854">헤어질 결심</a>,
 <a class="link_txt" href="/moviedb/main?movieId=152991">룸 쉐어링</a>,
 <a class="link_txt" href="/moviedb/main?movieId=109937">니 부모 얼굴이 보고 싶다</a>,
 <a class="link_txt" href="/moviedb/main?movieId=156501">로스트 시티</a>,
 <a class="link_txt" href="/moviedb/main?movieId=153828">모어</a>,
 <a class="link_txt" href="/moviedb/main?movieId=145325">니얼굴</a>,
 <a class="link_txt" href="/moviedb/main?movieId=151102">애프터 양</a>,
 <a class="link_txt" data-tiara-layer="home" href="/main">홈</a>,
 <a class="link_txt" data-tiara-layer="ranking" href="/ranking/reservation">랭킹</a>,
 <a class="link_txt" data-tiara-layer="premovie" href="/premovie/theater">상영예정작</a>,
 <a class="link_txt" data-tiara-layer="contents" href="/contents/news">콘텐츠</a>]

In [6]:
li_lists

[<a class="link_txt" href="/moviedb/main?movieId=114329">탑건: 매버릭</a>,
 <a class="link_txt" href="/moviedb/main?movieId=146758">마녀(魔女) Part2. The Other One</a>,
 <a class="link_txt" href="/moviedb/main?movieId=122749">범죄도시 2</a>,
 <a class="link_txt" href="/moviedb/main?movieId=144096">브로커</a>,
 <a class="link_txt" href="/moviedb/main?movieId=155087">버즈 라이트이어</a>,
 <a class="link_txt" href="/moviedb/main?movieId=139235">쥬라기 월드: 도미니언</a>,
 <a class="link_txt" href="/moviedb/main?movieId=160414">극장판 윌벤져스 : 수상한 캠핑 대소동</a>,
 <a class="link_txt" href="/moviedb/main?movieId=47111">극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미</a>,
 <a class="link_txt" href="/moviedb/main?movieId=144854">헤어질 결심</a>,
 <a class="link_txt" href="/moviedb/main?movieId=152991">룸 쉐어링</a>,
 <a class="link_txt" href="/moviedb/main?movieId=109937">니 부모 얼굴이 보고 싶다</a>,
 <a class="link_txt" href="/moviedb/main?movieId=156501">로스트 시티</a>,
 <a class="link_txt" href="/moviedb/main?movieId=153828">모어</a>,
 <a class="link_txt" href="/moviedb/main?movieId=145325">니얼굴</a>,
 <a class="link_txt" href="/moviedb/main?movieId=151102">애프터 양</a>,
 <a class="link_txt" data-tiara-layer="home" href="/main">홈</a>,
 <a class="link_txt" data-tiara-layer="ranking" href="/ranking/reservation">랭킹</a>,
 <a class="link_txt" data-tiara-layer="premovie" href="/premovie/theater">상영예정작</a>,
 <a class="link_txt" data-tiara-layer="contents" href="/contents/news">콘텐츠</a>]

In [7]:
# 데이터 프레임을 만들려면 일단 list 로 만들자
    # R 처럼 list를 만들고 데이터프레임을 만들기

count = 0
titleLists = [] # 영화 제목 List
countLists = [] # 순위 List

for list in li_lists:
    count += 1
    print(count, list.string.strip())
    countLists.append(count)
    titleLists.append(list.string.strip())

1 탑건: 매버릭
2 마녀(魔女) Part2. The Other One
3 범죄도시 2
4 브로커
5 버즈 라이트이어
6 쥬라기 월드: 도미니언
7 극장판 윌벤져스 : 수상한 캠핑 대소동
8 극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미
9 헤어질 결심
10 룸 쉐어링
11 니 부모 얼굴이 보고 싶다
12 로스트 시티
13 모어
14 니얼굴
15 애프터 양
16 홈
17 랭킹
18 상영예정작
19 콘텐츠

In [8]:
# List 확인

print(countLists)
print(titleLists)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
['탑건: 매버릭', '마녀(魔女) Part2. The Other One', '범죄도시 2', '브로커', '버즈 라이트이어', '쥬라기 월드: 도미니언', '극장판 윌벤져스 : 수상한 캠핑 대소동', '극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미', '헤어질 결심', '룸 쉐어링', '니 부모 얼굴이 보고 싶다', '로스트 시티', '모어', '니얼굴', '애프터 양', '홈', '랭킹', '상영예정작', '콘텐츠']

In [9]:
# countLists만으로 DataFrame 생성

df = pd.DataFrame(data=countLists, columns=['순위'])
df

    순위
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11
11  12
12  13
13  14
14  15
15  16
16  17
17  18
18  19

In [10]:
# 기존 DataFrame에 컬럼과 List 추가
    # 파이썬에선 벡터값을 Series라고 한다.
df['영화제목'] = pd.Series(titleLists)
df

    순위                            영화제목
0    1                         탑건: 매버릭
1    2     마녀(魔女) Part2. The Other One
2    3                          범죄도시 2
3    4                             브로커
4    5                        버즈 라이트이어
5    6                    쥬라기 월드: 도미니언
6    7           극장판 윌벤져스 : 수상한 캠핑 대소동
7    8  극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미
8    9                          헤어질 결심
9   10                           룸 쉐어링
10  11                  니 부모 얼굴이 보고 싶다
11  12                          로스트 시티
12  13                              모어
13  14                             니얼굴
14  15                           애프터 양
15  16                               홈
16  17                              랭킹
17  18                           상영예정작
18  19                             콘텐츠

In [11]:
# CSV로 저장하기
    # 중요! 인덱스는 안쓸거니까 False로 한다
df.to_csv("../Data/DaumList.csv", encoding='utf-8', index= False)

In [12]:
# 잘 저장되어있는지 불러와서 확인하기
pd.read_csv("../Data/DaumList.csv")

    순위                            영화제목
0    1                         탑건: 매버릭
1    2     마녀(魔女) Part2. The Other One
2    3                          범죄도시 2
3    4                             브로커
4    5                        버즈 라이트이어
5    6                    쥬라기 월드: 도미니언
6    7           극장판 윌벤져스 : 수상한 캠핑 대소동
7    8  극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미
8    9                          헤어질 결심
9   10                           룸 쉐어링
10  11                  니 부모 얼굴이 보고 싶다
11  12                          로스트 시티
12  13                              모어
13  14                             니얼굴
14  15                           애프터 양
15  16                               홈
16  17                              랭킹
17  18                           상영예정작
18  19                             콘텐츠

In [13]:
from bs4 import BeautifulSoup
from urllib.request import urlopen
import pandas as pd

url = "https://movie.naver.com/movie/sdb/rank/rmovie.naver"
page = urlopen(url)
soup = BeautifulSoup(page, 'html.parser')

In [14]:
naver_lists = soup.select("#old_content > table > tbody > tr > td.title > div > a")
naver_lists

[<a href="/movie/bi/mi/basic.naver?code=81888" title="탑건: 매버릭">탑건: 매버릭</a>,
 <a href="/movie/bi/mi/basic.naver?code=196367" title="마녀(魔女) Part2. The Other One">마녀(魔女) Part2. The Other One</a>,
 <a href="/movie/bi/mi/basic.naver?code=192608" title="범죄도시2">범죄도시2</a>,
 <a href="/movie/bi/mi/basic.naver?code=196854" title="브로커">브로커</a>,
 <a href="/movie/bi/mi/basic.naver?code=198413" title="헤어질 결심">헤어질 결심</a>,
 <a href="/movie/bi/mi/basic.naver?code=182016" title="닥터 스트레인지: 대혼돈의 멀티버스">닥터 스트레인지: 대혼돈의 멀티버스</a>,
 <a href="/movie/bi/mi/basic.naver?code=214603" title="버즈 라이트이어">버즈 라이트이어</a>,
 <a href="/movie/bi/mi/basic.naver?code=191646" title="쥬라기 월드: 도미니언">쥬라기 월드: 도미니언</a>,
 <a href="/movie/bi/mi/basic.naver?code=187347" title="토르: 러브 앤 썬더">토르: 러브 앤 썬더</a>,
 <a href="/movie/bi/mi/basic.naver?code=10100" title="탑건">탑건</a>,
 <a href="/movie/bi/mi/basic.naver?code=210031" title="실종">실종</a>,
 <a href="/movie/bi/mi/basic.naver?code=216100" title="그대가 조국">그대가 조국</a>,
 <a href="/movie/bi/mi/basic.naver?code=198472" title="니얼굴">니얼굴</a>,
 <a href="/movie/bi/mi/basic.naver?code=216171" title="룸 쉐어링">룸 쉐어링</a>,
 <a href="/movie/bi/mi/basic.naver?code=213487" title="극장판 윌벤져스 : 수상한 캠핑 대소동">극장판 윌벤져스 : 수상한 캠핑 대소동</a>,
 <a href="/movie/bi/mi/basic.naver?code=192151" title="외계+인 1부">외계+인 1부</a>,
 <a href="/movie/bi/mi/basic.naver?code=195758" title="헌트">헌트</a>,
 <a href="/movie/bi/mi/basic.naver?code=194196" title="한산: 용의 출현">한산: 용의 출현</a>,
 <a href="/movie/bi/mi/basic.naver?code=218055" title="두개의 눈">두개의 눈</a>,
 <a href="/movie/bi/mi/basic.naver?code=218223" title="스파이더헤드">스파이더헤드</a>,
 <a href="/movie/bi/mi/basic.naver?code=50368" title="극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미">극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미</a>,
 <a href="/movie/bi/mi/basic.naver?code=216482" title="미친 능력">미친 능력</a>,
 <a href="/movie/bi/mi/basic.naver?code=217720" title="더 킬러: 죽어도 되는 아이">더 킬러: 죽어도 되는 아이</a>,
 <a href="/movie/bi/mi/basic.naver?code=175322" title="마녀">마녀</a>,
 <a href="/movie/bi/mi/basic.naver?code=10128" title="디어 헌터">디어 헌터</a>,
 <a href="/movie/bi/mi/basic.naver?code=159812" title="니 부모 얼굴이 보고 싶다">니 부모 얼굴이 보고 싶다</a>,
 <a href="/movie/bi/mi/basic.naver?code=213733" title="극장판 주술회전 0">극장판 주술회전 0</a>,
 <a href="/movie/bi/mi/basic.naver?code=208144" title="모어">모어</a>,
 <a href="/movie/bi/mi/basic.naver?code=191634" title="미니언즈2">미니언즈2</a>,
 <a href="/movie/bi/mi/basic.naver?code=209738" title="뒤틀린 집">뒤틀린 집</a>,
 <a href="/movie/bi/mi/basic.naver?code=208431" title="컴온 컴온">컴온 컴온</a>,
 <a href="/movie/bi/mi/basic.naver?code=194598" title="리멤버 미">리멤버 미</a>,
 <a href="/movie/bi/mi/basic.naver?code=184519" title="비상선언">비상선언</a>,
 <a href="/movie/bi/mi/basic.naver?code=201810" title="아부쟁이">아부쟁이</a>,
 <a href="/movie/bi/mi/basic.naver?code=213539" title="개들의 도시">개들의 도시</a>,
 <a href="/movie/bi/mi/basic.naver?code=208772" title="카시오페아">카시오페아</a>,
 <a href="/movie/bi/mi/basic.naver?code=217472" title="엘비스">엘비스</a>,
 <a href="/movie/bi/mi/basic.naver?code=212082" title="감동주의보">감동주의보</a>,
 <a href="/movie/bi/mi/basic.naver?code=214611" title="민스미트 작전">민스미트 작전</a>,
 <a href="/movie/bi/mi/basic.naver?code=164122" title="신비한 동물들과 덤블도어의 비밀">신비한 동물들과 덤블도어의 비밀</a>,
 <a href="/movie/bi/mi/basic.naver?code=201335" title="고스트랜드">고스트랜드</a>,
 <a href="/movie/bi/mi/basic.naver?code=216272" title="경아의 딸">경아의 딸</a>,
 <a href="/movie/bi/mi/basic.naver?code=201848" title="센티그레이드">센티그레이드</a>,
 <a href="/movie/bi/mi/basic.naver?code=213555" title="잭 인 더 박스">잭 인 더 박스</a>,
 <a href="/movie/bi/mi/basic.naver?code=190374" title="앵커">앵커</a>,
 <a href="/movie/bi/mi/basic.naver?code=216495" title="그레이 맨">그레이 맨</a>,
 <a href="/movie/bi/mi/basic.naver?code=213535" title="더 렛지">더 렛지</a>,
 <a href="/movie/bi/mi/basic.naver?code=190695" title="모비우스">모비우스</a>,
 <a href="/movie/bi/mi/basic.naver?code=213478" title="우스운게 딱! 좋아!">우스운게 딱! 좋아!</a>,
 <a href="/movie/bi/mi/basic.naver?code=213451" title="큐브">큐브</a>]

In [15]:
# 데이터 프레임을 만들려면 일단 list 로 만들자
    # R 처럼 list를 만들고 데이터프레임을 만들기

count = 0
titleLists = [] # 영화 제목 List
countLists = [] # 순위 List

for list in naver_lists:
    count += 1
    print(count, list.string.strip())
    countLists.append(count)
    titleLists.append(list.string.strip())

1 탑건: 매버릭
2 마녀(魔女) Part2. The Other One
3 범죄도시2
4 브로커
5 헤어질 결심
6 닥터 스트레인지: 대혼돈의 멀티버스
7 버즈 라이트이어
8 쥬라기 월드: 도미니언
9 토르: 러브 앤 썬더
10 탑건
11 실종
12 그대가 조국
13 니얼굴
14 룸 쉐어링
15 극장판 윌벤져스 : 수상한 캠핑 대소동
16 외계+인 1부
17 헌트
18 한산: 용의 출현
19 두개의 눈
20 스파이더헤드
21 극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미
22 미친 능력
23 더 킬러: 죽어도 되는 아이
24 마녀
25 디어 헌터
26 니 부모 얼굴이 보고 싶다
27 극장판 주술회전 0
28 모어
29 미니언즈2
30 뒤틀린 집
31 컴온 컴온
32 리멤버 미
33 비상선언
34 아부쟁이
35 개들의 도시
36 카시오페아
37 엘비스
38 감동주의보
39 민스미트 작전
40 신비한 동물들과 덤블도어의 비밀
41 고스트랜드
42 경아의 딸
43 센티그레이드
44 잭 인 더 박스
45 앵커
46 그레이 맨
47 더 렛지
48 모비우스
49 우스운게 딱! 좋아!
50 큐브

In [16]:
# List 확인

print(countLists)
print(titleLists)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
['탑건: 매버릭', '마녀(魔女) Part2. The Other One', '범죄도시2', '브로커', '헤어질 결심', '닥터 스트레인지: 대혼돈의 멀티버스', '버즈 라이트이어', '쥬라기 월드: 도미니언', '토르: 러브 앤 썬더', '탑건', '실종', '그대가 조국', '니얼굴', '룸 쉐어링', '극장판 윌벤져스 : 수상한 캠핑 대소동', '외계+인 1부', '헌트', '한산: 용의 출현', '두개의 눈', '스파이더헤드', '극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미', '미친 능력', '더 킬러: 죽어도 되는 아이', '마녀', '디어 헌터', '니 부모 얼굴이 보고 싶다', '극장판 주술회전 0', '모어', '미니언즈2', '뒤틀린 집', '컴온 컴온', '리멤버 미', '비상선언', '아부쟁이', '개들의 도시', '카시오페아', '엘비스', '감동주의보', '민스미트 작전', '신비한 동물들과 덤블도어의 비밀', '고스트랜드', '경아의 딸', '센티그레이드', '잭 인 더 박스', '앵커', '그레이 맨', '더 렛지', '모비우스', '우스운게 딱! 좋아!', '큐브']

In [17]:
# countLists만으로 DataFrame 생성

df = pd.DataFrame(data=countLists, columns=['Index'])
df

    Index
0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8
8       9
9      10
10     11
11     12
12     13
13     14
14     15
15     16
16     17
17     18
18     19
19     20
20     21
21     22
22     23
23     24
24     25
25     26
26     27
27     28
28     29
29     30
30     31
31     32
32     33
33     34
34     35
35     36
36     37
37     38
38     39
39     40
40     41
41     42
42     43
43     44
44     45
45     46
46     47
47     48
48     49
49     50

In [18]:
# 기존 DataFrame에 컬럼과 List 추가
    # 파이썬에선 벡터값을 Series라고 한다.
df['Titles'] = pd.Series(titleLists)
df

    Index                          Titles
0       1                         탑건: 매버릭
1       2     마녀(魔女) Part2. The Other One
2       3                           범죄도시2
3       4                             브로커
4       5                          헤어질 결심
5       6             닥터 스트레인지: 대혼돈의 멀티버스
6       7                        버즈 라이트이어
7       8                    쥬라기 월드: 도미니언
8       9                     토르: 러브 앤 썬더
9      10                              탑건
10     11                              실종
11     12                          그대가 조국
12     13                             니얼굴
13     14                           룸 쉐어링
14     15           극장판 윌벤져스 : 수상한 캠핑 대소동
15     16                         외계+인 1부
16     17                              헌트
17     18                       한산: 용의 출현
18     19                           두개의 눈
19     20                          스파이더헤드
20     21  극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미
21     22                           미친 능력
22     23                 더 킬러: 죽어도 되는 아이
23     24                              마녀
24     25                           디어 헌터
25     26                  니 부모 얼굴이 보고 싶다
26     27                      극장판 주술회전 0
27     28                              모어
28     29                           미니언즈2
29     30                           뒤틀린 집
30     31                           컴온 컴온
31     32                           리멤버 미
32     33                            비상선언
33     34                            아부쟁이
34     35                          개들의 도시
35     36                           카시오페아
36     37                             엘비스
37     38                           감동주의보
38     39                         민스미트 작전
39     40               신비한 동물들과 덤블도어의 비밀
40     41                           고스트랜드
41     42                           경아의 딸
42     43                          센티그레이드
43     44                        잭 인 더 박스
44     45                              앵커
45     46                           그레이 맨
46     47                            더 렛지
47     48                            모비우스
48     49                     우스운게 딱! 좋아!
49     50                              큐브

In [19]:
# CSV로 저장하기
    # 중요! 인덱스는 안쓸거니까 False로 한다
df.to_csv("../Data/naverRanking.csv", encoding='utf-8', index= False)

In [20]:
# 잘 저장되어있는지 불러와서 확인하기
naverRanking = pd.read_csv("../Data/naverRanking.csv")

In [21]:
naverRanking.head()

   Index                       Titles
0      1                      탑건: 매버릭
1      2  마녀(魔女) Part2. The Other One
2      3                        범죄도시2
3      4                          브로커
4      5                       헤어질 결심